# Generated by Django 5.0.1 on 2026-01-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_cartitem_quantity_alter_orderitem_quantity"),
        ("products", "0004_alter_product_stock_quantity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="unit_value",
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "unit_value")},
        ),
    ]
