# Generated by Django 4.2.7 on 2026-02-20 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_cartitem_unique_together_cartitem_unit_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelledOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "cancelled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "cancelled_orders",
            },
        ),
    ]
