# Generated by Django 4.2.7 on 2026-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="pincode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
