# Generated by Django 5.0.1 on 2026-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description"),
            preserve_default=False,
        ),
    ]
