# Generated by Django 5.0.1 on 2026-01-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
