# Generated by Django 4.2.7 on 2026-01-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="stock_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
