# Generated by Django 4.2.7 on 2026-01-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productvariant_stock_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fruits", "Fruits"),
                    ("Vegetables", "Vegetables"),
                    ("Dairy", "Dairy"),
                    ("Grains", "Grains"),
                    ("Spices", "Spices"),
                    ("Veg starters", "Veg starters"),
                    ("Non Veg starters", "Non Veg starters"),
                    ("Biryani", "Biryani"),
                    ("Pulao", "Pulao"),
                    ("Veg thali", "Veg thali"),
                    ("Non veg Thali", "Non veg Thali"),
                    ("Sweets", "Sweets"),
                    ("Snacks", "Snacks"),
                    ("Dry fruits", "Dry fruits"),
                    ("Tiffins", "Tiffins"),
                    ("Drinks", "Drinks"),
                    ("Desserts", "Desserts"),
                    ("Millets", "Millets"),
                    ("Pulses", "Pulses"),
                    ("Flours", "Flours"),
                    ("Tea Powders", "Tea Powders"),
                    ("Rice", "Rice"),
                    ("Oils", "Oils"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
