# Generated by Django 4.2.7 on 2026-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoScrollImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField()),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("placement", models.CharField(max_length=50)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "auto_scroll_images",
                "ordering": ["order"],
                "managed": False,
            },
        ),
    ]
