# Generated by Django 5.0.1 on 2026-01-07 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_useraddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Clothes", "Clothes"),
                            ("Money", "Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Received", "Received"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "item_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="donations/items/"
                    ),
                ),
                ("pickup_address", models.TextField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="donations/payments/"
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "donations",
                "ordering": ["-created_at"],
            },
        ),
    ]
