# Generated by Django 5.0.1 on 2026-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="description",
            field=models.TextField(default="No description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="donation",
            name="item_image",
            field=models.ImageField(
                default="donations/items/default.jpg", upload_to="donations/items/"
            ),
            preserve_default=False,
        ),
    ]
