# Generated by Django 4.2.7 on 2026-01-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_alter_donation_description_alter_donation_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="profession",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="time_slot",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Clothes", "Clothes"),
                    ("Money", "Money"),
                    ("Education", "Education"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="item_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="donations/items/"
            ),
        ),
    ]
