# Generated by Django 5.0.1 on 2026-01-05 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=20, unique=True)),
                ("password_hash", models.TextField()),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Customer", "Customer"),
                            ("Vendor", "Vendor"),
                            ("Women Merchant", "Women Merchant"),
                        ],
                        max_length=30,
                    ),
                ),
                ("address_line", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("state", models.CharField(blank=True, max_length=120, null=True)),
                ("country", models.CharField(blank=True, max_length=120, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("profile_pic_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "user_profiles",
                "managed": False,
            },
        ),
    ]
