# Generated by Django 5.0.1 on 2026-01-07 05:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Label for address e.g., Home, Work", max_length=255
                    ),
                ),
                ("address_line", models.TextField()),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("country", models.CharField(default="India", max_length=120)),
                ("pincode", models.CharField(max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_addresses",
            },
        ),
    ]
