# Generated by Django 5.0.1 on 2026-01-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_useraddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraddress",
            old_name="city",
            new_name="town_city",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="address_line",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="name",
        ),
        migrations.AddField(
            model_name="useraddress",
            name="area_street_sector",
            field=models.CharField(
                default="", help_text="Area, Street, Sector, Village", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="delivery_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="flat_house_building",
            field=models.CharField(
                default="",
                help_text="Flat, House no., Building, Company, Apartment",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="full_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="landmark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="mobile_number",
            field=models.CharField(default="", max_length=20),
        ),
    ]
