# Generated by Django 4.2.7 on 2026-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_city_useraddress_town_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="google_maps_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
