name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get Packages
        run: flutter pub get

      - name: Precache iOS
        run: flutter precache --ios

      - name: Patch Razorpay iOS Plugin
        run: |
          FILE="$HOME/.pub-cache/hosted/pub.dev/razorpay_flutter-1.4.5/ios/Classes/RazorpayDelegate.swift"

          echo "Checking file..."
          ls -l "$FILE"

          echo "Removing subscribeToAnalyticsEvents..."
          sed -i '' '/subscribeToAnalyticsEvents/d' "$FILE"

          echo "Patched successfully."

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          mkdir Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          cd Payload
          zip -r ../app.ipa .
          cd ..

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: app.ipa